import { SpaceData } from "../../engine/state/space";
import { BLUE, RED, YELLOW, PURPLE } from "../../engine/state/good";
import { Direction } from "../../engine/state/tile";
import { duplicate } from "../../utils/functions";
import {
  black,
  city,
  grid,
  plain,
  PLAIN,
  WATER,
  town,
  UNPASSABLE,
  white,
} from "../factory";

export const map = grid<SpaceData>([
    [...duplicate(16, WATER)],
    [
      ...duplicate(6, WATER),
      town("Vaasa"),  
      ...duplicate(2, PLAIN),
      city("Pori", BLUE, [white(6)]),
      plain({ unpassableEdges: [Direction.TOP] }),
      town("Rauma"),
      PLAIN,
      city("Turku", BLUE, [black(1)]),
      ...duplicate(2, WATER),
    ],
    [
      ...duplicate(7, WATER),
      ...duplicate(8, PLAIN), 
      WATER,
    ],
    [
      ...duplicate(5, WATER),
      town("Kokkola"),
      PLAIN,
      town("Seinäjoki"),
      ...duplicate(7, PLAIN),
      WATER,
    ],  
    [
      ...duplicate(5, WATER),
      ...duplicate(6, PLAIN),
      city("Tampere", PURPLE, [white(5)]),
      ...duplicate(2, PLAIN),
      city("Espoo",RED, [black(2)]),
      WATER,
    ],
    [
      PLAIN,
      ...duplicate(2, WATER),
      town("Raahe"),
      ...duplicate(8, PLAIN),
      town("Hämeenlinna"),
      PLAIN,
      city("Helsinki", BLUE, [black(3)]),
      WATER,
    ],
    [
      UNPASSABLE,  
      PLAIN,
      WATER,
      ...duplicate(11, PLAIN),
      city("Vantaa", RED, [black(4)]),
      WATER,  
    ],
    [
      ...duplicate(2, PLAIN),
      city("Oulu", YELLOW, [white(1)]),
      ...duplicate(6, PLAIN),
      city("Jyväskylä", RED, [white(4)]),
      ...duplicate(2, PLAIN),
      city("Lahti", BLUE, [black(5)]),
      PLAIN,
        ...duplicate(2, WATER),
    ],
    [
      UNPASSABLE,
      ...duplicate(13, PLAIN),
      ...duplicate(2, WATER),
    ],
    [
      ...duplicate(5, PLAIN),
      town("Iisalmi"),
      PLAIN,
      city("Kuopio", PURPLE, [white(3)]),
      ...duplicate(2, PLAIN),
      town("Mikkeli"),
      ...duplicate(2, PLAIN),
      town("Kotka"),
      ...duplicate(2, WATER),
    ],
    [
      UNPASSABLE,
      town("Taivalkoski"),
      ...duplicate(2, PLAIN),
      town("Kajaani"),
      ...duplicate(7, PLAIN),
      city("Lappeenranta", RED, [black(6)]),
      PLAIN,
      ...duplicate(2, WATER),
    ],
    [
      ...duplicate(10, PLAIN),  
      town("Savonlinna"),
      ...duplicate(2, PLAIN),
      ...duplicate(3, WATER),
    ],
    [
      UNPASSABLE,
      ...duplicate(7, PLAIN),
      city("Joensuu", YELLOW, [white(2)]),
      ...duplicate(3, PLAIN),
      ...duplicate(4, UNPASSABLE),
    ],
    [
      ...duplicate(4, UNPASSABLE),
      ...duplicate(7, PLAIN),
      ...duplicate(5, UNPASSABLE),
    ],
]);
