import { SpaceData, CityData } from "../../engine/state/space";
import { BLUE, RED, YELLOW, PURPLE } from "../../engine/state/good";
import { Direction } from "../../engine/state/tile";
import { duplicate } from "../../utils/functions";
import {
  black,
  city,
  grid,
  plain,
  PLAIN,
  WATER,
  town,
  UNPASSABLE,
  white,
} from "../factory";
import { RUSSIA, SWEDEN } from "./russia_sweden"


export const map = grid<SpaceData>([
    [...duplicate(16, WATER)],
    [
      ...duplicate(6, WATER),
      town("Vaasa"),  
      ...duplicate(2, PLAIN),
      city("Pori", BLUE, [white(6)]),
      plain({ unpassableEdges: [Direction.TOP] }),
      town("Rauma"),
      PLAIN,
      city("Turku", BLUE, [black(1)]),
      ...duplicate(2, WATER),
    ],
    [
      ...duplicate(6, WATER),
      ...duplicate(6, PLAIN), 
      plain({ unpassableEdges: [Direction.BOTTOM, Direction.BOTTOM_LEFT] }),
      PLAIN,
      plain({ unpassableEdges: [Direction.TOP_LEFT, Direction.BOTTOM_RIGHT] }),
      WATER,
    ],
    [
      ...duplicate(5, WATER),
      town("Kokkola"),
      PLAIN,
      town("Seinäjoki"),
      ...duplicate(3, PLAIN),
      plain({ unpassableEdges: [Direction.TOP, Direction.TOP_RIGHT] }),
      ...duplicate(3, PLAIN),
      WATER,
    ],  
    [
      SWEDEN,
      ...duplicate(4, WATER),
      ...duplicate(5, PLAIN),
      plain({ unpassableEdges: [Direction.TOP, Direction.TOP_RIGHT, Direction.BOTTOM_RIGHT] }),
      city("Tampere", PURPLE, [white(5)]),
      ...duplicate(2, PLAIN),
      city("Espoo",RED, [black(2)]),
      WATER,
    ],
    [
      PLAIN,
      ...duplicate(2, WATER),
      town("Raahe"),
      ...duplicate(3, PLAIN),
      plain({ unpassableEdges: [Direction.TOP_LEFT, Direction.BOTTOM_LEFT] }),
      ...duplicate(3, PLAIN),
      plain({ unpassableEdges: [Direction.TOP, Direction.TOP_LEFT, Direction.BOTTOM_LEFT] }),
      town("Hämeenlinna"),
      PLAIN,
      city("Helsinki", BLUE, [black(3)]),
      WATER,
    ],
    [
      UNPASSABLE,  
      PLAIN,
      WATER,
      ...duplicate(7, PLAIN),
      plain({ unpassableEdges: 
        [
          Direction.TOP_LEFT,
          Direction.TOP, 
          Direction.TOP_RIGHT, 
          Direction.BOTTOM_RIGHT,
          Direction.BOTTOM
        ] }),
      ...duplicate(3, PLAIN),
      city("Vantaa", RED, [black(4)]),
      WATER,  
    ],
    [
      ...duplicate(2, PLAIN),
      city("Oulu", YELLOW, [white(1)]),
      ...duplicate(3, PLAIN),
      plain({ unpassableEdges: [Direction.TOP, Direction.BOTTOM] }),
      plain({ unpassableEdges: 
        [
          Direction.TOP_LEFT,
          Direction.TOP_RIGHT, 
          Direction.BOTTOM_RIGHT,
          Direction.BOTTOM
        ] }),
      PLAIN,
      city("Jyväskylä", RED, [white(4)]),
      plain({ unpassableEdges: [Direction.TOP, Direction.BOTTOM_LEFT, Direction.BOTTOM_RIGHT] }),
      plain({ unpassableEdges: [Direction.TOP_LEFT, Direction.BOTTOM_LEFT] }),
      city("Lahti", BLUE, [black(5)]),
      PLAIN,
        ...duplicate(2, WATER),
    ],
    [
      UNPASSABLE,
      ...duplicate(3, PLAIN),
      plain({ unpassableEdges: [Direction.TOP_RIGHT, Direction.BOTTOM_RIGHT] }),
      PLAIN,
      plain({ unpassableEdges: [Direction.BOTTOM_RIGHT] }),
      plain({ unpassableEdges: [Direction.TOP_RIGHT, Direction.BOTTOM] }),
      plain({ unpassableEdges: [Direction.BOTTOM_LEFT, Direction.BOTTOM] }),
      PLAIN,
      plain({ unpassableEdges: [Direction.TOP_RIGHT, Direction.BOTTOM_RIGHT, Direction.BOTTOM] }),
      plain({ unpassableEdges: [Direction.BOTTOM] }),
      ...duplicate(2, PLAIN),
      ...duplicate(2, WATER),
    ],
    [
      ...duplicate(3, PLAIN),
      plain({ unpassableEdges: [Direction.BOTTOM] }),
      PLAIN,
      town("Iisalmi"),
      PLAIN,
      city("Kuopio", PURPLE, [white(3)]),
      ...duplicate(2, PLAIN),
      
      town("Mikkeli"),
      plain({ unpassableEdges: [Direction.BOTTOM_RIGHT] }),
      PLAIN,
      town("Kotka"),
      ...duplicate(2, WATER),
    ],
    [
      UNPASSABLE,
      town("Taivalkoski"),
      ...duplicate(2, PLAIN),
      town("Kajaani"),
      plain({ unpassableEdges: [Direction.TOP] }),
      PLAIN,
      plain({ unpassableEdges: 
        [
          Direction.BOTTOM_LEFT,
          Direction.BOTTOM
        ] }),
      plain({ unpassableEdges: 
        [
          Direction.TOP_LEFT,
          Direction.TOP_RIGHT,
          Direction.BOTTOM_RIGHT,
          Direction.BOTTOM_LEFT,
        ] }),
      plain({ unpassableEdges: [Direction.BOTTOM_RIGHT] }),
      plain({ unpassableEdges: [Direction.TOP_RIGHT] }),
      plain({ unpassableEdges: 
        [
          Direction.TOP_LEFT,
          Direction.BOTTOM_RIGHT,
          Direction.BOTTOM,
          Direction.BOTTOM_LEFT,
        ] }),
      city("Lappeenranta", RED, [black(6)]),
      PLAIN,
      ...duplicate(2, WATER),
    ],
    [
      ...duplicate(2, PLAIN),  
      plain({ unpassableEdges: [Direction.TOP_RIGHT, Direction.BOTTOM_RIGHT] }),
      plain({ unpassableEdges: [Direction.BOTTOM, Direction.BOTTOM_RIGHT] }),
      plain({ unpassableEdges: [Direction.TOP_RIGHT, Direction.BOTTOM_RIGHT] }),
      PLAIN,
      plain({ unpassableEdges: [Direction.TOP_RIGHT, Direction.BOTTOM_RIGHT] }),
      plain({ unpassableEdges: [Direction.BOTTOM] }),
      plain({ unpassableEdges: [Direction.TOP_RIGHT, Direction.BOTTOM] }),
      plain({ unpassableEdges: [Direction.BOTTOM, Direction.TOP_RIGHT] }),
      town("Savonlinna"),
      plain({ unpassableEdges: [Direction.TOP, Direction.BOTTOM_LEFT] }),
      PLAIN,
      ...duplicate(3, WATER),
    ],
    [
      UNPASSABLE,
      ...duplicate(3, PLAIN),
      plain({ unpassableEdges: [Direction.BOTTOM] }),
      PLAIN,
      plain({ unpassableEdges: [Direction.BOTTOM] }),
      plain({ unpassableEdges: 
        [
          Direction.TOP_RIGHT,
          Direction.BOTTOM_RIGHT,
          Direction.BOTTOM,
        ] }),
      city("Joensuu", YELLOW, [white(2)]),
      plain({ unpassableEdges: 
        [
          Direction.TOP,
          Direction.TOP_RIGHT,
          Direction.BOTTOM,
        ] }),
      plain({ unpassableEdges: [Direction.TOP_RIGHT, Direction.BOTTOM_RIGHT] }),
      plain({ unpassableEdges: [Direction.TOP_LEFT] }),
      UNPASSABLE,
      RUSSIA,
      ...duplicate(2, UNPASSABLE),
    ],
    [
      ...duplicate(4, UNPASSABLE),
      ...duplicate(7, PLAIN),
      ...duplicate(5, UNPASSABLE),
    ],
]);
